# Generated by Django 3.2.9 on 2022-03-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_name', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=35)),
                ('mobile_number', models.IntegerField(max_length=15)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
